LPS-141370
david-gutierrez-mesa/liferay-portal pull request #207
Opened 2021-11-19 13:52 UTC by catarineaguiar

2021-11-19 13:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-11-19 13:52 UTC, catarineaguiar commented
ci:test:sf

2021-11-19 13:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/837/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/837/jenkins-report.html">here</a>.</b></p>

2021-11-19 13:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5e76ec51fa2debb85aae5166162507dc8b7c31eb">5e76ec51fa2debb85aae5166162507dc8b7c31eb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/catarineaguiar/liferay-portal/tree/LPS-141370">LPS-141370</a><br/>Branch GIT ID: <a href="https://github.com/catarineaguiar/liferay-portal/commit/b17a2998d21f8163299e9e9c7305e221ac4241a9">b17a2998d21f8163299e9e9c7305e221ac4241a9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/837/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/837/jenkins-report.html">here</a>.</h5></details></html>

2021-11-22 09:53 UTC, david-gutierrez-mesa requested changes

2021-11-22 09:53 UTC, david-gutierrez-mesa commented on modules/apps/site-initializer/site-initializer-masterclass/site-initializer-masterclass-test/src/testFunctional/tests/Masterclass.testcase
> +			Staging.gotoNavTab(tabName = "Display Page Templates");
why staging?

2021-11-22 09:53 UTC, david-gutierrez-mesa commented on modules/apps/site-initializer/site-initializer-masterclass/site-initializer-masterclass-test/src/testFunctional/tests/Masterclass.testcase
> +			Staging.gotoNavTab(tabName = "Display Page Templates");
why Staging?

2021-11-22 09:53 UTC, david-gutierrez-mesa commented on modules/apps/site-initializer/site-initializer-masterclass/site-initializer-masterclass-test/src/testFunctional/tests/Masterclass.testcase
> +			Navigator._gotoPage(pageName = "Blog");
Macros with _ should only be used inside the files where they are defined. Try to find another similar method in Navigator

2021-11-22 16:35 UTC, david-gutierrez-mesa commented
ci:forward

2021-11-22 16:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-11-22 16:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1140/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1140/jenkins-report.html">here</a>.</b></p>

2021-11-22 16:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4ceac20a949a25b57642f3a9179f556524154eb0">4ceac20a949a25b57642f3a9179f556524154eb0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/catarineaguiar/liferay-portal/tree/LPS-141370">LPS-141370</a><br/>Branch GIT ID: <a href="https://github.com/catarineaguiar/liferay-portal/commit/5921a033f8b5c2b151ab27527575e1f6437951a9">5921a033f8b5c2b151ab27527575e1f6437951a9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/782/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/782/jenkins-report.html">here</a>.</h5></details></html>

2021-11-22 16:39 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/782//consoleFull)

2021-11-22 16:39 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110218
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/782//consoleFull)

2021-11-22 16:39 UTC, closed without merging

2021-11-22 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/782/">test-portal-source-format#782</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/782/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/david-gutierrez-mesa/liferay-portal/pull/207">david-gutierrez-mesa#207</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1582134014">[master] ci:test:sf - catarineaguiar &gt; david-gutierrez-mesa - PR#207 - 2021-11-22[08:36:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/2558/">publish-testray-report#2558</a><br/></div></div>

2021-11-22 16:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1140/">test-portal-acceptance-pullrequest(master)#1140</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1140/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/david-gutierrez-mesa/liferay-portal/pull/207">david-gutierrez-mesa#207</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1582134023">[master] ci:test:relevant - catarineaguiar &gt; david-gutierrez-mesa - PR#207 - 2021-11-22[08:36:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/3488/">publish-testray-report#3488</a><br/></div></div>